question_data = [
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which character is from &quot;Splatoon&quot;?",
        "correct_answer": "Marie",
        "incorrect_answers": ["Cyrus", "Palutena", "Shulk"],
    },
    {
        "category": "History",
        "type": "multiple",
        "difficulty": "medium",
        "question": "In what year was the last natural case of smallpox documented?",
        "correct_answer": "1977",
        "incorrect_answers": ["1982", "1980", "1990"],
    },
    {
        "category": "Geography",
        "type": "multiple",
        "difficulty": "easy",
        "question": "How many countries does the United States share a land border with?",
        "correct_answer": "2",
        "incorrect_answers": ["1", "3", "4"],
    },
    {
        "category": "Entertainment: Film",
        "type": "multiple",
        "difficulty": "medium",
        "question": "What type of cheese, loved by Wallace and Gromit, had it&#039;s sale prices rise after their successful short films?",
        "correct_answer": "Wensleydale",
        "incorrect_answers": ["Cheddar", "Moon Cheese", "Edam"],
    },
    {
        "category": "Science: Mathematics",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What is the correct order of operations for solving equations?",
        "correct_answer": "Parentheses, Exponents, Multiplication, Division, Addition, Subtraction",
        "incorrect_answers": [
            "Addition, Multiplication, Division, Subtraction, Addition, Parentheses",
            "Parentheses, Exponents, Addition, Substraction, Multiplication, Division",
            "The order in which the operations are written.",
        ],
    },
    {
        "category": "Entertainment: Film",
        "type": "multiple",
        "difficulty": "medium",
        "question": "What is the name of the queen&#039;s pet in A Bug&#039;s Life?",
        "correct_answer": "Aphie",
        "incorrect_answers": ["Flik", "Hopper", "Dot"],
    },
    {
        "category": "Entertainment: Music",
        "type": "multiple",
        "difficulty": "easy",
        "question": "How many strings are there on a cello?",
        "correct_answer": "4",
        "incorrect_answers": ["5", "6", "8"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Who is the main character in One Piece?",
        "correct_answer": "Luffy",
        "incorrect_answers": ["Shanks", "Zoro", "Smoker"],
    },
    {
        "category": "Vehicles",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What country was the Trabant 601 manufactured in?",
        "correct_answer": "East Germany",
        "incorrect_answers": ["Soviet Union", "Hungary", "France"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "medium",
        "question": "In the ARPG &quot;Path of Exile,&quot; what is the highest amount of sockets that an item can have?",
        "correct_answer": "6",
        "incorrect_answers": ["5", "4", "8"],
    },
]
